export const LIST_SET_TREE_STATE = "LIST/SET_TREE_STATE";
export const LIST_SET_SEARCH_STATE = "LIST/SET_SEARCH_STATE";
export const LIST_SET_PAGINATION_STATE = "LIST/SET_PAGINATION_STATE";
export const LIST_SET_UI_STATE = "LIST/SET_UI_STATE";
export const LIST_CLEAR_TREE_SELECTION = "LIST/CLEAR_TREE_SELECTION";
export const LIST_RESET_STATE = "LIST/RESET_STATE";
