export const PROJECT_LIST_SET_TREE_STATE = "PROJECT_LIST_SET_TREE_STATE";
export const PROJECT_LIST_SET_SEARCH_STATE = "PROJECT_LIST_SET_SEARCH_STATE";
export const PROJECT_LIST_SET_PAGINATION_STATE =
	"PROJECT_LIST_SET_PAGINATION_STATE";
export const PROJECT_LIST_SET_UI_STATE = "PROJECT_LIST_SET_UI_STATE";
export const PROJECT_LIST_CLEAR_TREE_SELECTION =
	"PROJECT_LIST_CLEAR_TREE_SELECTION";
export const PROJECT_LIST_RESET_STATE = "PROJECT_LIST_RESET_STATE";
